version: '3.8'
services:
  mariadb:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - .:/uniroster-server
    environment:
      MYSQL_ROOT_PASSWORD: password
  uniroster:
    container_name: uniroster-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "80:80"
    volumes:
      - .:/uniroster-server